# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Login dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image
      run: docker build -t hoangtheanh2002hhbg/cloudcomputing .
    - name: Publish image
      run: docker push hoangtheanh2002hhbg/cloudcomputing
    - name: save data
      run: |
          echo '{"info": "your data here"}' > data.json
          curl -X POST -d @data.json -H "Content-Type: application/json" "https://f2e4-14-231-31-53.ngrok-free.app/ci-result"
      env:
        DEBUG: true

  deploy:
    needs: build
    runs-on: theanh124
    steps:
      - name: Pull image
        run: sudo docker pull hoangtheanh2002hhbg/cloudcomputing
      - name: Remove old container
        run: sudo docker rm -f cloudcomputing-container
      - name: Run image
        run: sudo docker run -d -p 80:8080 --name cloudcomputing-container -t hoangtheanh2002hhbg/cloudcomputing
      - name: Logs
        run: sudo docker logs cloudcomputing-container